// pages/search.js
import Head from 'next/head';
import { useState } from 'react';
import Home from './index';

export default function Search() {
  const [searchTerm, setSearchTerm] = useState('');

  const handleSearchChange = (e) => {
    setSearchTerm(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home searchTerm={searchTerm} handleSearchChange={handleSearchChange} />
    </>
  );
}
